// <auto-generated />
using System;
using LibraryInfrastructure.Controllers;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace SalaryInfrastructure.Migrations
{
    [DbContext(typeof(DbSalaryContext))]
    partial class DbSalaryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LibraryInfrastructure.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("Facultyid")
                        .HasColumnType("integer")
                        .HasColumnName("facultyid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("Updatedat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updatedat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("department_pkey");

                    b.HasIndex("Facultyid");

                    b.ToTable("department", (string)null);
                });

            modelBuilder.Entity("LibraryInfrastructure.Models.Faculty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("Updatedat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updatedat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("faculty_pkey");

                    b.ToTable("faculty", (string)null);
                });

            modelBuilder.Entity("LibraryInfrastructure.Models.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Basesalary")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("basesalary");

                    b.Property<DateTime?>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("Updatedat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updatedat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("position_pkey");

                    b.ToTable("position", (string)null);
                });

            modelBuilder.Entity("LibraryInfrastructure.Models.Salaryfund", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Calculationdate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("calculationdate")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("Departmentid")
                        .HasColumnType("integer")
                        .HasColumnName("departmentid");

                    b.Property<int?>("Facultyid")
                        .HasColumnType("integer")
                        .HasColumnName("facultyid");

                    b.Property<DateOnly>("Periodend")
                        .HasColumnType("date")
                        .HasColumnName("periodend");

                    b.Property<DateOnly>("Periodstart")
                        .HasColumnType("date")
                        .HasColumnName("periodstart");

                    b.Property<decimal?>("Totalamount")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("totalamount");

                    b.Property<DateTime?>("Updatedat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updatedat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("salaryfund_pkey");

                    b.HasIndex("Departmentid");

                    b.HasIndex("Facultyid");

                    b.ToTable("salaryfund", (string)null);
                });

            modelBuilder.Entity("LibraryInfrastructure.Models.Salaryhistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Changedate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("changedate")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal?>("Newsalary")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("newsalary");

                    b.Property<decimal?>("Oldsalary")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("oldsalary");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<int?>("Scientistid")
                        .HasColumnType("integer")
                        .HasColumnName("scientistid");

                    b.HasKey("Id")
                        .HasName("salaryhistory_pkey");

                    b.HasIndex("Scientistid");

                    b.ToTable("salaryhistory", (string)null);
                });

            modelBuilder.Entity("LibraryInfrastructure.Models.Scientist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("Departmentid")
                        .HasColumnType("integer")
                        .HasColumnName("departmentid");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("fullname");

                    b.Property<decimal>("Salary")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("salary");

                    b.Property<DateTime?>("Updatedat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updatedat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("scientist_pkey");

                    b.HasIndex("Departmentid");

                    b.ToTable("scientist", (string)null);
                });

            modelBuilder.Entity("LibraryInfrastructure.Models.Scientistposition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Departmentid")
                        .HasColumnType("integer")
                        .HasColumnName("departmentid");

                    b.Property<decimal?>("Employmentrate")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)")
                        .HasDefaultValue(1.0m)
                        .HasColumnName("employmentrate");

                    b.Property<DateOnly?>("Enddate")
                        .HasColumnType("date")
                        .HasColumnName("enddate");

                    b.Property<int?>("Positionid")
                        .HasColumnType("integer")
                        .HasColumnName("positionid");

                    b.Property<int?>("Scientistid")
                        .HasColumnType("integer")
                        .HasColumnName("scientistid");

                    b.Property<DateOnly>("Startdate")
                        .HasColumnType("date")
                        .HasColumnName("startdate");

                    b.HasKey("Id")
                        .HasName("scientistposition_pkey");

                    b.HasIndex("Departmentid");

                    b.HasIndex("Positionid");

                    b.HasIndex("Scientistid");

                    b.ToTable("scientistposition", (string)null);
                });

            modelBuilder.Entity("LibraryInfrastructure.Models.Department", b =>
                {
                    b.HasOne("LibraryInfrastructure.Models.Faculty", "Faculty")
                        .WithMany("Departments")
                        .HasForeignKey("Facultyid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("department_facultyid_fkey");

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("LibraryInfrastructure.Models.Salaryfund", b =>
                {
                    b.HasOne("LibraryInfrastructure.Models.Department", "Department")
                        .WithMany("Salaryfunds")
                        .HasForeignKey("Departmentid")
                        .HasConstraintName("salaryfund_departmentid_fkey");

                    b.HasOne("LibraryInfrastructure.Models.Faculty", "Faculty")
                        .WithMany("Salaryfunds")
                        .HasForeignKey("Facultyid")
                        .HasConstraintName("salaryfund_facultyid_fkey");

                    b.Navigation("Department");

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("LibraryInfrastructure.Models.Salaryhistory", b =>
                {
                    b.HasOne("LibraryInfrastructure.Models.Scientist", "Scientist")
                        .WithMany("Salaryhistories")
                        .HasForeignKey("Scientistid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("salaryhistory_scientistid_fkey");

                    b.Navigation("Scientist");
                });

            modelBuilder.Entity("LibraryInfrastructure.Models.Scientist", b =>
                {
                    b.HasOne("LibraryInfrastructure.Models.Department", "Department")
                        .WithMany("Scientists")
                        .HasForeignKey("Departmentid")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("scientist_departmentid_fkey");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("LibraryInfrastructure.Models.Scientistposition", b =>
                {
                    b.HasOne("LibraryInfrastructure.Models.Department", "Department")
                        .WithMany("Scientistpositions")
                        .HasForeignKey("Departmentid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("scientistposition_departmentid_fkey");

                    b.HasOne("LibraryInfrastructure.Models.Position", "Position")
                        .WithMany("Scientistpositions")
                        .HasForeignKey("Positionid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("scientistposition_positionid_fkey");

                    b.HasOne("LibraryInfrastructure.Models.Scientist", "Scientist")
                        .WithMany("Scientistpositions")
                        .HasForeignKey("Scientistid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("scientistposition_scientistid_fkey");

                    b.Navigation("Department");

                    b.Navigation("Position");

                    b.Navigation("Scientist");
                });

            modelBuilder.Entity("LibraryInfrastructure.Models.Department", b =>
                {
                    b.Navigation("Salaryfunds");

                    b.Navigation("Scientistpositions");

                    b.Navigation("Scientists");
                });

            modelBuilder.Entity("LibraryInfrastructure.Models.Faculty", b =>
                {
                    b.Navigation("Departments");

                    b.Navigation("Salaryfunds");
                });

            modelBuilder.Entity("LibraryInfrastructure.Models.Position", b =>
                {
                    b.Navigation("Scientistpositions");
                });

            modelBuilder.Entity("LibraryInfrastructure.Models.Scientist", b =>
                {
                    b.Navigation("Salaryhistories");

                    b.Navigation("Scientistpositions");
                });
#pragma warning restore 612, 618
        }
    }
}
